services:
  backend:
    volumes:
      - ./backend/:/backend

    command:
      [ "tail", "-F", "/dev/null" ]
      # [
      #   "uv",
      #   "run",
      #   "uvicorn",
      #   "--host",
      #   "0.0.0.0",
      #   "--port",
      #   "8000",
      #   "app.main:app",
      #   "--reload"
      # ]
