on: 
  push:
  pull_request:
      branches:
        - master

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install uv deps
        run: uv sync --frozen
        working-directory: backend
      - name: Run linter check
        run: uv run ./scripts/lint.sh
        working-directory: backend
